<a href="https://colab.research.google.com/github/manavbahuguna/manavbahuguna/blob/main/Random_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

To create a tensor of all zeros


In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Create tensor of ones

In [ ]:
luls = torch.ones(size=(3,4))
luls

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
luls.dtype

torch.float32

Create a range of tensors and tensors like

In [ ]:
# Use torch range or arange\
one_to_ten = torch.arange(start = 1, end = 11, step=  1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
on_to_twn = torch.arange( start = 00, end = 100, step= 20)
on_to_twn

tensor([ 0, 20, 40, 60, 80])

Create tensor like


In [ ]:
ten_zeros = torch.zeros_like(input = one_to_ten)
# This makes all tensor zero but takes the size and shape of input tensor
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATATYPE

In [ ]:
#FLOAT 32 TENSOR
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype = None, # what datatype your tensor is off
                               device= None,# what device your tensor is on like cpu,cuda etc
                               requires_grad= False)# whether or not to track gradients with this tensor operation
float_32_tensor
# float 32 is used for higher precision and genral computataion
# float 16 used in dl to reduce memory footprintand sped up computation

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float16

Problems usually run into in tensor / dl
1] Tensor not being right daqtatype
2] Tensor not bein g right shape
3] Tensor not being on right devixe

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_torch_32 =torch.tensor([3,6,9],dtype=torch.int32)
int_torch_32

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_16_tensor * int_torch_32

tensor([ 9., 36., 81.], dtype=torch.float16)

Problems usually run into in tensor / dl 1] Tensor not being right daqtatype 2] Tensor not bein g right shape 3] Tensor not being on right device The solution is that for shape we can use tensor.shape() , for device we can select the device we want and for datatype we can select the right datatype



In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3346, 0.9496, 0.6387, 0.1678],
        [0.5617, 0.0217, 0.0607, 0.4593],
        [0.9879, 0.5991, 0.9756, 0.3015]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3346, 0.9496, 0.6387, 0.1678],
        [0.5617, 0.0217, 0.0607, 0.4593],
        [0.9879, 0.5991, 0.9756, 0.3015]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu



Tensors manipulation






In [ ]:
# Matrix Multiplication (very imp) used in neural networks and DL
# element multplication also used in neural networks and DL (basic mul)
# First Element Multiplication
print(tensor, * tensor)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-23-1a41c0fd3d99>, line 4)